// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgv8BBT_WBJf_RfuumW3qDrxsO9oCQ648',
    appId: '1:992892545100:web:af66605a03f08325b06ce9',
    messagingSenderId: '992892545100',
    projectId: 'moonlangdictionary',
    authDomain: 'moonlangdictionary.firebaseapp.com',
    storageBucket: 'moonlangdictionary.firebasestorage.app',
    measurementId: 'G-PH0NW4D12B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgNPAYDF-AoGe_ppWytKh-DNPkfmcpsA4',
    appId: '1:992892545100:android:3e1f6f0f418d1477b06ce9',
    messagingSenderId: '992892545100',
    projectId: 'moonlangdictionary',
    storageBucket: 'moonlangdictionary.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRkO-7MviimMKQnUNylLVMKtc07UcAOUE',
    appId: '1:992892545100:ios:01e77e5e3cf52b63b06ce9',
    messagingSenderId: '992892545100',
    projectId: 'moonlangdictionary',
    storageBucket: 'moonlangdictionary.firebasestorage.app',
    iosBundleId: 'com.example.moonlangDictionary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRkO-7MviimMKQnUNylLVMKtc07UcAOUE',
    appId: '1:992892545100:ios:01e77e5e3cf52b63b06ce9',
    messagingSenderId: '992892545100',
    projectId: 'moonlangdictionary',
    storageBucket: 'moonlangdictionary.firebasestorage.app',
    iosBundleId: 'com.example.moonlangDictionary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgv8BBT_WBJf_RfuumW3qDrxsO9oCQ648',
    appId: '1:992892545100:web:ade487204b2ec9d6b06ce9',
    messagingSenderId: '992892545100',
    projectId: 'moonlangdictionary',
    authDomain: 'moonlangdictionary.firebaseapp.com',
    storageBucket: 'moonlangdictionary.firebasestorage.app',
    measurementId: 'G-QZQEHN66JR',
  );
}
